### ISSUE TITLE
Feature request: add two buttons to play the user input voice and TTS for the words or sentence

### ISSUE THREAD

**Issue by valuex** [warleysr/ankipa#1]
What's a great add-on AnkiPA is!
Is it possible to add two buttons to play the user input voice and TTS for the words or sentence?

**Comment by warleysr** [comment]
Very useful request. I added the replay option in 021ce4ad438a8ad09b566823c087a1c64a0c9792. The button to play TTS already exists but I will need more time to work on it. I'm wondering if I use OS based TTS or Azure Speech Service (which means additional work to get the key to configure the addon). I appreciate any thoughts on this.

**Comment by warleysr** [comment]
I found out that the same key can be used to generate TTS audios in Azure, so I decided to go that way and the functionality is working since d242790. I need to find a solution for removing the temporary files that this process generate because the Anki player blocks it.

**Comment by warleysr** [comment]
Fixed and completed implemented in 172eda6.
