### ISSUE TITLE
Erro de conexão

### ISSUE THREAD

**Issue by adveduardo** [warleysr/ankipa#10]
Boa noite! Estou recebendo essa mensagem.
Procurei mas não encontrei um tutorial para criar uma chave api, do qual acredito ser o problema gerado. 

Desde já muito obrigado

There was a service error recognizing your speech.

• Check if your microphone is working well and recording clearly.

• Make sure the text that you are pronuncing is in the correct field and configured language. Take a look at the Settings.

• Check debug.json file in your addon's folder and contact me on GitHub if you need help: [github.com/warleysr/ankipa](https://github.com/warleysr/ankipa)

**Comment by warleysr** [comment]
Boa noite. Para criar sua chave na API acesse o site da Microsoft Azure e clique em 'Inicio gratuito': 
https://azure.microsoft.com/pt-br/free/

Depois de criada sua conta, crie um serviço de fala, será necessário selecionar a região (selecione **brazilsouth**) e depois de criar você terá acesso as chaves. Lembre-se de configurar a chave e essa mesma região na configuração do add-on.

Você pode tentar usar a chave de teste que está na descrição também. Tente seguir estes passos e comenta aqui se não conseguir.
