### ISSUE TITLE
How to create API?

### ISSUE THREAD

**Issue by dochypermoose** [warleysr/ankipa#11]
Unless I'm missing something is there no way to get the API for free? I don't see a "create a new resource" option

![image](https://github.com/warleysr/ankipa/assets/25800800/62feb9cd-0718-4714-9fff-5a0957db5264)

**Comment by warleysr** [comment]
Hello, you need to choose an Azure subscription first. You can select the free trial for 12 months by clicking on the first **Start** button or use the Student benefits if you have a student email.
