### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by yitzhakbg** [warleysr/ankipa#14]
First, kudos on this lovely addon. Requests:
1. Statistics are presently shown globally, for all profiles. If there are multiple users (profiles), can statistics be shown for each profile individually?
2. Can the results page be shown in the language of the user interface?

**Comment by warleysr** [comment]
Great suggestions.

 I'm not familiar with profiles in Anki, so I need to take a look on that, but I can do it, maybe just configuring the profile in the addon itself.

About the user interface, all strings are hardcoded in English so it need some effort to change. Which language are you aiming for? Maybe we can work together on a translation file.

**Comment by yitzhakbg** [comment]
Maybe we can work together in a wider sense. I have a vision for
introducing Anki into education. Can wfe talk?
Yitzhak
https://www.linkedin.com/in/yitzhakbg/
