### ISSUE TITLE
Card window does not respond to clicks

### ISSUE THREAD

**Issue by Vlad78** [warleysr/ankipa#3]
Hi! Thank for you work. Is it possible to make card window accessible for interactions when result window is opened?
![2023-01-08_19-04-57](https://user-images.githubusercontent.com/23346524/211207042-2f14dcfb-f356-4dd1-8868-82e54719d823.jpg)

**Comment by warleysr** [comment]
Fixed in 141b116, please update your addon. Thanks for the feedback.
