### ISSUE TITLE
Update instructions for macOS

### ISSUE THREAD

**Issue by bmulholland** [warleysr/ankipa#5]
On macOS the hotkey is Cmd+W, not Ctrl+W (as the README/instructions say). I was hesitant to hit Cmd+W because that is a shortcut to close windows.

I'm not a fan of the shortcut, because it does override the "close window" shortcut. At least if the instructions said the correct shortcut, though, I'd have known what to try.

**Comment by warleysr** [comment]
Good to know. I really didn't thought about the Mac users. I will try to implement something in config to the user himself define the preferred shortcut.

**Comment by warleysr** [comment]
I implemented this in d93f615. Please update your addon. For Mac it will always be _Cmd_ instead of _Ctrl_. Added this info in the README. Thanks for reporting.
