### ISSUE TITLE
There was a service error recognizing your speech. Try again.

### ISSUE THREAD

**Issue by bmulholland** [warleysr/ankipa#6]
I get that error after recording. I'm confident my settings are correct. I'm happy to try to debug myself, but the error doesn't provide anything I can dig into. I don't see any obvious debug logging [in the code](https://github.com/warleysr/ankipa/blob/d93f615c4fb80e272530b032b3a4845a702a7616/ankipa.py#L86) to look at, either. Any tips on how to diagnose? Is there a way to debug in anki itself?

**Comment by warleysr** [comment]
I definitely should have put more detailed error messages. But this specific one occurs when `RESULT["RecognitionStatus"] != "Success"`, so basically the Azure service is returning the JSON data but their services couldn't recognize the speech.

 I would recommend you to check the `Field index` parameter in Settings and also look at your flashcard. This parameter defines which field of your card the addon will collect the text to evaluate your pronunciation. So let's say it has the default value `0`, it means that the first field of your flashcard need to have a sentence in the targeting language.

Also, check in another app if your mic is working well and recording clear. Sometimes when my mic is a little bit far it can't recognize. 

Try this and tell me if it had some effect. I don't know how to debug in Anki unfortunately, but soon I will provide someway to catch more information about the errors.

**Comment by warleysr** [comment]
In 41b5205 I implemented a generation of a file to give more details when this error occurs. If after trying the things above and the error persists, update your addon (cloning the repo, I didn't updated at AnkiWeb.net) and loog at the **debug.json** file in the addon's folder.

**Comment by bmulholland** [comment]
Looks like it was at least partly my airpods: I tried recording with my laptop's mic instead and now I get a new error. Thanks for all your help here (and the addon, it's super cool!).

Re: the field index, this is a little tricky. I have quite a few different cards, so there's not one consistent field index to use. For me, a better option would be something like a prioritized list of field names to use. Do you have any thoughts on that? I'd be happy to take a stab at implementing it if we can align on approach.

**Comment by warleysr** [comment]
Your idea sounds great and much more user friendly. When doing `mw.reviewer.card.note()` it already returns a dict representing the fields, so its very easy to implement something like that, except for the GUI part I think. I'm new to Qt and can't realize how to build a graphical interface for a prioritized list. Feel free for trying this out.

**Comment by bmulholland** [comment]
I'm thinking just making it comma separated. So just need to split on commas, trim whitespace on the ends, and then try them in order. And I guess fall back on field index 0? I'll try this out once I've got the basics working (i.e. for a single card type)

**Comment by bmulholland** [comment]
Closing this one out for now: there's debug logging, which can help with the error that's the subject of the ticket. For user-friendliness, you may want to consider improving the error message -- maybe just drop in the hints you told me above?

I'll file a separate issue for field index improvements.
