### ISSUE TITLE
macOS: argument 1 has unexpected type 'bool'

### ISSUE THREAD

**Issue by bmulholland** [warleysr/ankipa#7]
I'm guessing this one has something to do with it being a mac, though maybe it's the Qt version change?

Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 13.1
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-01-17 10:20:33
Add-ons possibly involved: ⁨AnkiPA - Pronunciation Assessment for Anki⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.sound", line 623, in and_then
  File "aqt.sound", line 552, in stop
  File "aqt.sound", line 765, in after_record
  File "/Users/bmulholland/Library/Application Support/Anki2/addons21/86363097/ankipa.py", line 162, in after_record
    widget.setWindowModality(False)
TypeError: setWindowModality(self, Qt.WindowModality): argument 1 has unexpected type 'bool'

**Comment by bmulholland** [comment]
No, looks like the method takes the same arg in both Qt5 and Qt6. Not sure why it would work for you (maybe False gets resolved to 0 somehow?). [Here's the enum that the method expects](https://doc.qt.io/qt-5/qt.html#WindowModality-enum) -- I assume it's the same for any object you'd call this on.

**Comment by warleysr** [comment]
I changed this in 153938f. Working on Qt5 (again I didn't payed attention to the other versions). Hope this works in Qt6 as well.

**Comment by bmulholland** [comment]
I'm not sure how to install from Github, could you push to Anki's addon database?

**Comment by warleysr** [comment]
Sure. Done!

**Comment by bmulholland** [comment]
Similar error, but says it's an int not a bool. Looking at [Anki's source](https://github.com/ankitects/anki/search?q=setWindowModality), I think the line needs to be `widget.setWindowModality(Qt.WindowModality.NonModal)`

**Comment by warleysr** [comment]
Ok, I will install the Qt6 version myself to make this works on both version.

**Comment by warleysr** [comment]
Well, it was pretty simple actually. I thought I would need to do a workaround but seems that the Anki provided Qt interface works well for both versions. Now working on Qt5 and Qt6. Update your addon again.

**Comment by bmulholland** [comment]
Fantastic! I'll check tomorrow :)

**Comment by bmulholland** [comment]
Confirmed fixed! Thanks again :)
