### ISSUE TITLE
File index improvements: name instead of index, and multi-card support

### ISSUE THREAD

**Issue by bmulholland** [warleysr/ankipa#8]
Forked from https://github.com/warleysr/ankipa/issues/6#issuecomment-1385189183:

> Re: the field index, this is a little tricky. I have quite a few different cards, so there's not one consistent field index to use. For me, a better option would be something like a prioritized list of field names to use. Do you have any thoughts on that? I'd be happy to take a stab at implementing it if we can align on approach.

> Your idea sounds great and much more user friendly. When doing mw.reviewer.card.note() it already returns a dict representing the fields, so its very easy to implement something like that, except for the GUI part I think. I'm new to Qt and can't realize how to build a graphical interface for a prioritized list. Feel free for trying this out.

> I'm thinking just making it comma separated. So just need to split on commas, trim whitespace on the ends, and then try them in order. And I guess fall back on field index 0? I'll try this out once I've got the basics working (i.e. for a single card type)

**Comment by warleysr** [comment]
Implemented this in c61aa1a. Much more user friendly. Thanks for the suggestion.
