### ISSUE TITLE
price of Azure's price

### ISSUE THREAD

**Issue by YELLOWHOMEIN** [warleysr/ankipa#9]
Hi, I want to know the price of Azure's API. I browsed their website but did not find the price. Is it free? Your addon is wonderful anyway.

**Comment by YELLOWHOMEIN** [comment]
<img width="956" alt="image" src="https://user-images.githubusercontent.com/27610409/221392053-78375072-896b-4bdf-8e86-3a867e6cedb1.png">

**Comment by warleysr** [comment]
Hi, thanks for your feedback. 

The pronunciation assessment has the same price of Speech-to-text service. With the free account you have 5 audio hours per month, which is equivalent of 10 minutes per day (of voice recording) for 30 days. 

More than that you will pay $1 per extra hour, but I think you need to change the type of your account and add a credit card.

You can check the price in this link: https://azure.microsoft.com/en-gb/pricing/details/cognitive-services/speech-services/

**Comment by YELLOWHOMEIN** [comment]
thank you!
